### ISSUE TITLE
Issue with Meteor 1.0.2

### ISSUE THREAD

**Issue by Anonyfox** [aldeed/meteor-http-extras#5]
Seems that something strange happened. Currently I have no clue why exactly this happens, it started after upgrading from meteor 1.0.1 to 1.0.2. 

```
Error: Cannot find module 'request'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.Npm.require
```
